### ISSUE TITLE
Making resizabled and draggabled work together

### ISSUE THREAD

**Issue by JSkjoldahl** [Yang-Tang/shinyjqui#10]
Hi!

First of all, thanks for a great package which have helped me a lot! Cool features. 
I'm currently struggling to get jqui_resizabled and jqui_resizabled to work together correctly. 
The problem is that if I drag the object the resizable button/icon doesn't follow along. 

Here is an example
```
library(shiny)
library(highcharter)

server <- function(input, output) {
  output$foo <- renderHighchart({
    hchart(mtcars, "scatter", hcaes(x = cyl, y = mpg))
  })
  output$position <- renderPrint({
    print(input$foo_position)
  })
}
ui <- fluidPage(
  verbatimTextOutput('position'),
  jqui_resizabled(jqui_draggabled(highchartOutput('foo', width = '800px', height = '800px')))
)

shinyApp(ui, server)
```

Is there a way to solve this problem?

Cheers

**Comment by Yang-Tang** [comment]
Hi @JSkjoldahl , thank you for submit the issue! I'll push an update to fix it.

**Comment by JSkjoldahl** [comment]
Great, that was quick! 
Thanks
