### ISSUE TITLE
Scrollbar in Selectinputs not working with draggable modal

### ISSUE THREAD

**Issue by shosaco** [Yang-Tang/shinyjqui#11]
When trying to scroll through the options in a draggable modal, the modal is moved instead of the options scrolled (the click is highjacked by shinyjqui):

```
library(shiny)
library(shinyjqui)

ui <- fluidPage()

server <- function(input, output){
    showModal(
      jqui_draggabled(
        modalDialog(
          selectInput("choose", "Choose", choices = 1:10)
      )
     )
    )
}

shinyApp(ui = ui, server = server)
```

![image](https://user-images.githubusercontent.com/20717764/30424104-23f1e88a-9945-11e7-839b-ef74d54a0e68.png)

**Comment by Yang-Tang** [comment]
Hi @shosaco , draggable has a `cancel` option to address this problem. By default, it will prevent dragging from starting on `input`, `textarea`, `button`, `select` and `option` elements, but some shiny inputs, including the `selectInput` here, are not in this list. To add all the shiny inputs in the cancel list, you can add a `cancel` option like this:
```
library(shiny)
library(shinyjqui)

ui <- fluidPage()

server <- function(input, output){
  showModal(
    jqui_draggabled(
      modalDialog(
        selectInput("choose", "Choose", choices = 1:10)
      ),
      options = list(cancel = ".shiny-input-container")  
    )
  )
}

shinyApp(ui = ui, server = server)
```
The above code prevent dragging from any shiny input inside the `modalDialog`. The `shiny-input-container` is a class name that shared by all the shiny inputs.

**Comment by shosaco** [comment]
Great, thank you!
