### ISSUE TITLE
Making resizabled and draggabled work with Shiny Bookmarking

### ISSUE THREAD

**Issue by JSkjoldahl** [Yang-Tang/shinyjqui#12]
Hi again, 

Again, thanks for such a great package! I really love how the user is able to customise the layout using the resizabled and draggabled functions. 

I was wondering if there is a way to make the resizabled and draggabled functions work with Shiny Bookmarking in such a way that the user can restore previous layout settings he/she made. 

For example suppose the user changes the size and position of the plot in this small Shiny App

```
library(shiny)
library(highcharter)

server <- function(input, output, server) {
  output$foo <- renderHighchart({
    hchart(mtcars, "scatter", hcaes(x = cyl, y = mpg))
  })
  output$position <- renderPrint({
    print(input$foo_position)
  })
}
ui <- function(request){ fluidPage(
  bookmarkButton(),
  verbatimTextOutput('position'),
  jqui_resizabled(jqui_draggabled(highchartOutput('foo', width = '800px', height = '800px')))
)}

shinyApp(ui, server, enableBookmarking = "server") # Or use url instead!

```

I have no idea how this could be done, or if it possible at all. 

Cheers

**Comment by Yang-Tang** [comment]
It's a bit complicated. I'll try to figure out a way to do that.

**Comment by JSkjoldahl** [comment]
Thank you so much for taking the time to have a look at it. 
Will be looking forward to hearing from you! 

Cheers

**Comment by Yang-Tang** [comment]
The bookmarking feature has been enabled since version 0.3.0, so I will close this issue.
