### ISSUE TITLE
How to undo / remove a draged element for orderInput?

### ISSUE THREAD

**Issue by happyshows** [Yang-Tang/shinyjqui#16]
Hi,

I'm wondering if user make a mistake on dragging from source to dest, how does s/he fix the issue without refresh the application?

**Comment by Yang-Tang** [comment]
Hi @happyshows , sorry for the late reply.
Thank you for the good suggestion! It's not possible currently. I'm now trying to make this possible together with issue #12 . But there seem to be many problems to solve. It's absolutely doable but may take some time...

**Comment by Yang-Tang** [comment]
The save/load feature, which has been enabled since version 0.3.0, can solve the problem, so I will close this issue.

**Comment by MayaGans** [comment]
Would you mind expanding on how to use the save/load feature in this context given the code:

```
server <- function(input, output) {
  output$order <- renderPrint({ print(input$dest_order) })
}

ui <- fluidPage(
  orderInput('source', 'Source', items = month.abb,
             as_source = TRUE, connect = 'dest'),
  orderInput('dest', 'Dest', items = NULL, placeholder = 'Drag items here...'),
  verbatimTextOutput('order')
)

shinyApp(ui, server)
```

Thank you so much for this amazing package!
