### ISSUE TITLE
jqui_draggable breaks bstooltip messages 

### ISSUE THREAD

**Issue by madmark81** [Yang-Tang/shinyjqui#19]
jqui_draggable breaks bstooltip messages it seems in the page/ space where an item is made dragable. 

While building an app in two stages, I discovered a conflict when trying to combine the two parts, some research showed it was the interaction between `bstooltips `and jqui_draggable code in my app. I pasted a minimal example to show the problem. 

using: 

see the test code for the scenario here: 
activate / disactivate the `jqui `lines of code to see the difference when hovering over `buttons`. 

A second point: How come `dragable `doesn't work on `actionButton`s? 

```

library("shiny")
library("shinyjqui")
library("shinyBS")
library("shinydashboard")
library("shinyjs")

shinyApp(

  ui = dashboardPage(title = "TestApp",
                     dashboardHeader(title = "TestApp"),
    dashboardSidebar(
      menuItem("Page1", tabName = "Tab1")), 
    
    dashboardBody(
      useShinyjs(),
      tabItems(
        tabItem( tabName = "Tab1",   
                 
                 
  h3("hello!"),
  actionButton("Click", "Click Me"),
  uiOutput("bstooltips")
  )))
  ),

  server =  function(input, output, session) {
    bsTooltip_Taglist <- tagList(
      bsTooltip(id = "Click", title = "This is a popup message", placement = "right", trigger = "hover", options= list(container = "body")),
      bsTooltip(id = "Dummybut", title = "This is a popup message", placement = "right", trigger = "hover", options= list(container = "body"))
      )

    bsTooltip_Taglist2 <- tagList(bsTooltip(id = "Dummybut", title = "This is a popup message", placement = "right", trigger = "hover", options= list(container = "body") ))
    
    output$popupmessage <- renderUI({  bsTooltip_Taglist2 })
    
    output$bstooltips <- renderUI({bsTooltip_Taglist})
    
    observeEvent(input$Click, {
      showModal(div(id="A_modal", modalDialog(
        inputId = "A_modaldialog",
        title = HTML('<span style="color:#339fff; font-size: 20px; font-weight:bold; font-family:sans-serif ">Modal Title<span>
                     <button type = "button" class="close" data-dismiss="modal" ">
                     <span style="color:#339fff; ">x <span>
                     </button> '),
        actionButton("Dummybut", "Dummybut"),
        uiOutput("popupmessage"),
        easyClose = TRUE,
        footer = NULL )))
      jqui_draggable(selector = '.modal-dialog')
      
    })
    
  #  jqui_draggable(selector = '#Click')  ### this line does: 1) not work on a button, and B) breaks the tooltip
    
    }
)
```

sessioninfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyjs_1.0          shinydashboard_0.6.1 shinyBS_0.61         shinyjqui_0.2.0      shiny_1.0.5         

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.9 compiler_3.4.3  R6_2.2.2        htmltools_0.3.6 tools_3.4.3     Rcpp_0.12.14    jsonlite_1.5    digest_0.6.13   xtable_1.8-2    httpuv_1.3.5    mime_0.5

**Comment by Yang-Tang** [comment]
Hi @madmark81 , this is an old bug of incompatible between `jquery-ui` and `bootstrap`. Actually, attaching `jquery-ui.js` itself is enough to break the tooltip without loading `shinyjqui`:
```
library(shiny)
library(shinyBS)

ui <- fluidPage(

  # load jquery-ui.js only by calling shiny::absolutePanel()
  absolutePanel("Drag me", draggable = TRUE), # This also breaks the tooltip
  actionButton("Click", "Click Me"),
  uiOutput("bstooltips")
)

server <- function(input, output, session) {
  
  bsTooltip_Taglist <- tagList(
    bsTooltip(id = "Click", 
              title = "This is a popup message", 
              placement = "right", 
              trigger = "hover", 
              options= list(container = "body"))
  )
  
  output$bstooltips <- renderUI({bsTooltip_Taglist})

}

shinyApp(ui, server)
```
Please refer to [this](https://stackoverflow.com/questions/23428285/bootstrap-and-jqueryui-conflict) for more details. 
Strictly speaking, this is a bug of `shinyBS`, you may rise an issue there.

**Comment by madmark81** [comment]
I guess I will try to use an alternative means to make tooltips to
circumvent the issue. Pitty that the two can't be used side by side.
If you have any suggestions what could be an alternative, i'd be happy to
hear them
