### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by maxheld83** [Yang-Tang/shinyjqui#2]
We're a little bit confused concerning the licensing situation of `shinyjqui`: [CRAN](https://cran.r-project.org/web/packages/shinyjqui/index.html) mentions an MIT license, but this repo includes no such information.

We obviously want to do right by the package author and be sure we're not using this in our own software without appropriate license.

Thanks!

**Comment by Yang-Tang** [comment]
Yes, I want this package to be under the MIT license. I declared the license type in `DESCRIPTION` file and added a `LICENSE` file with copy right holder. I'm new to R package writing. Did I miss something?

**Comment by maxheld83** [comment]
oh that is great news.

 I think some people *also* add the MIT License to the `LICENCE` on the repo, so people can figure out the license situation on GitHub as well. Like so: https://github.com/maxheld83/pensieve/blob/master/LICENSE

Anyway, thank you for this very generous and helpful addition to the shiny-verse 👍

**Comment by Yang-Tang** [comment]
@maxheld83 thank you for the help! I'll add the license.
