### ISSUE TITLE
Button appearance in orderInput

### ISSUE THREAD

**Issue by ismirsehregal** [Yang-Tang/shinyjqui#21]
Hi,
I just came across this great package and I started playing around with orderInput.
Is there a way to influence the appearance and information linked to the single buttons of the orderInput - besides changing the color for all buttons with item_class?
I'd like to add an id/color/icon argument for every item like [here](http://amitkohli.com/make-dashboard-tilesnotecards-in-r/).

Kind regards

**Comment by Yang-Tang** [comment]
Hi @ismirsehregal , sorry for the late reply.
The `orderInput` is based on the more flexible function `jqui_sortable`. You can use it to meet your request. 
In the following example, three buttons (div) with different id/color/icon were created using `jqui_sortable`. They will behave similar to the elements created by `orderInput`.
Please let me know if you want more features about this.
```
library(shiny)
library(shinyjqui)

server <- function(input, output) {
  
  output$order <- renderPrint({
    cat("Current order: \n")
    input$foo_order
  })
  
}

ui <- fluidPage(
  
  jqui_sortable(
    div(
      id = "foo",
      style = "font-size: 0px",
      
      div(id = "box1", icon("calendar"), "Text1", 
          class = "btn btn-primary", style = "margin: 1px"),
      div(id = "box2", icon("cog"), "Text2", 
          class = "btn btn-success", style = "margin: 1px"),
      div(id = "box3", icon("file"), "Text3", 
          class = "btn btn-info", style = "margin: 1px")
    )
  ),
  
  verbatimTextOutput("order")
  
)

shinyApp(ui, server)
```

**Comment by trafficonese** [comment]
This example throws an `Error in callback() : attempt to apply non-function` in the ui, with shinyjqui 0.2.0. When uncommenting the `jqui_sortable` it works fine. Why am I getting that error?
