### ISSUE TITLE
Dynamic item assigning to orderInput

### ISSUE THREAD

**Issue by dwitherell** [Yang-Tang/shinyjqui#22]
I am trying to figure out how to make an orderInput use a dynamically assigned list for its items - basically if option 1 is selected, show list 1s items, and if option 2 is selected, show list 2s items.

Everything seems to work as it should when it first loads, but once you switch the lists issues come up. The orderInput object itself updates, but the _order values do not change, and the orderInput object seems to lose it's "sortability" in the process (can no longer drag/move to sort items).

Is there something I am missing? Is there a non-orderInput route that could achieve this end result?

Below is some example code showing the issue:
```
library(shiny)
library(shinyjqui)

ui <- fluidPage(
    radioButtons(
        inputId = "test_list",
        label = "Item List Selection",
        choices = c("List1", "List2"),
        selected = "List1"
    ),
    uiOutput("test_sort"),
    br(),
    verbatimTextOutput('sort_order')
)

server <- function(input, output, session) {
    output$test_sort <- renderUI({
        req(input$test_list)
        
        if (input$test_list == "List1") {
            item_list <- c("1", "2", "3", "4")
        } else if (input$test_list == "List2") {
            item_list <- c("A", "B", "C", "D")
        } else {
            item_list <- "Error"
        }
        
        orderInput(inputId = 'test_sort_list',
                   label = "Testing",
                   items = item_list,
                   width = "100%",
                   class = "ui-sortable"
        )
    })

    output$sort_order <- renderPrint({
        input$test_sort_list_order
    })
}

shinyApp(
    ui = ui, 
    server = server
)
```

**Comment by Yang-Tang** [comment]
Hi @dwitherell , this is a bug of shinyjqui 0.2.0 which has been fixed in the current development version. You can install it from github and try again.

**Comment by dwitherell** [comment]
Hi @Yang-Tang -

Very nice, I tried it with the development version and it works as I would expect. Thanks for letting me know!

Any estimates on when the current development version will make it's way to CRAN? Just curious.

Thanks again!

**Comment by Yang-Tang** [comment]
Yes, I'm now trying to finish some documents for the new version. Hope it can be available on CRAN within one or two weeks. :)

**Comment by Yang-Tang** [comment]
Hi @dwitherell , just let you know the new version is now available on CRAN. Please feel free to try it and let me know if any new feature needed.
