### ISSUE TITLE
 function doesn't work in shinyApp

### ISSUE THREAD

**Issue by JAgOneill** [Yang-Tang/shinyjqui#25]
i have been using new update of this package (0.3.1) with R(3.5.1).
it doesn't give me any error though but , the function doesn't seem to work .
if i switch to old version(0.3.0) with R(3.5.1) it gives me an error( Error:attempt to apply `non-function)` 

`     warning: Error in callback: attempt to apply non-function
        81: callback
        80: shiny::insertUI
        79: sendMsg
        78: jqui_draggable
`

**Comment by Yang-Tang** [comment]
hi @JAgOneill ,  could you give an example about this?

**Comment by JAgOneill** [comment]
hello Yang-Tang ,
thank you for such a great package 
my shiny app is running on a supercomputer , here is my reproducible code
`tabPanel(
  title = "ID    ", id = "plotTab6999",
  br(),
  downloadButton("downloadPlot396663", "Save figure",style =  "color: #fff;background-color: gray;border-color:aquamarine"),
  br(), br(),
  jqui_resizable(plotOutput("name of output plot"))`



`
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6 `
`

`
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6
`
`
Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
`
`
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
`
`
attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     
`
`
other attached packages:
 [1] svgPanZoom_0.3.3      bindrcpp_0.2.2        shinyjqui_0.3.0       tibble_1.4.2          wakefield_0.3.3       highcharter_0.5.0    
 [7] pheatmap_1.0.10       ComplexHeatmap_1.18.1 circlize_0.4.4        ggvis_0.4.3           d3heatmap_0.6.1.2     tidyr_0.8.1          
[13] dplyr_0.7.6           plyr_1.8.4            magrittr_1.5          rintrojs_0.2.0        shinythemes_1.1.1     DT_0.4               
[19] plotly_4.7.1          ggplot2_3.0.0         shinyjs_1.0           shiny_1.1.0           edgeR_3.22.3          limma_3.36.2         
`
          ` loaded via a namespace (and not attached):
 [1] httr_1.3.1          jsonlite_1.5        viridisLite_0.3.0   assertthat_0.2.0    TTR_0.23-3          yaml_2.1.19         pillar_1.2.3       
 [8] lattice_0.20-35     rlist_0.4.6.1       glue_1.2.0          digest_0.6.15       RColorBrewer_1.1-2  promises_1.0.1      colorspace_1.3-2   
[15] htmltools_0.3.6     httpuv_1.4.4.2      psych_1.8.4         pkgconfig_2.0.1     GetoptLong_0.1.7    broom_0.4.5         purrr_0.2.5        
[22] xtable_1.8-2        scales_0.5.0        later_0.7.3         withr_2.1.2         sourcetools_0.1.7   lazyeval_0.2.1      quantmod_0.4-13    
[29] mnormt_1.5-5        crayon_1.3.4        mime_0.5            nlme_3.1-137        xts_0.10-2          foreign_0.8-70      rsconnect_0.8.8    
[36] tools_3.5.1         data.table_1.11.4   GlobalOptions_0.1.0 stringr_1.3.1       munsell_0.5.0       locfit_1.5-9.1      compiler_3.5.1     
[43] rlang_0.2.1         rstudioapi_0.7      rjson_0.2.20        htmlwidgets_1.2     crosstalk_1.0.0     igraph_1.2.1        labeling_0.3       
[50] base64enc_0.1-3     gtable_0.2.0        curl_3.2            reshape2_1.4.3      R6_2.2.2            zoo_1.8-2           lubridate_1.7.4    
[57] bindr_0.1.1         shape_1.4.4         stringi_1.2.3       parallel_3.5.1      Rcpp_0.12.17        png_0.1-7     png_0.1-7  tidyselect_0.2.4 `

**Comment by Yang-Tang** [comment]
Hi @JAgOneill I tried your code and found if id of a `plotOutput` contains white space (eg, "name of output plot" in your example), `jqui_resizable` will not work, but if the white spaces are removed (eg, changed to "name_of_output_plot"), the function will work again. Could you confirm whether the white spaces caused the problem in your development environment? Meanwhile, I'll try to fix this bug. Here is the code I'm using:

```
library(shiny)
library(shinyjqui)
library(ggplot2)

ui <- fluidPage(
  tabPanel(
    title = "ID ", id = "plotTab6999",
    br(),
    downloadButton(
      "downloadPlot396663", "Save figure",
      style = "color: #fff;background-color: gray;border-color:aquamarine"
    ),
    br(), br(),
    jqui_resizable(plotOutput("name_of_output_plot"))
  )
)

server <- function(input, output, session) {
  output$`name_of_output_plot` <- renderPlot({
    ggplot(mtcars, aes(x = cyl, y = mpg)) + geom_point()
  })
}

shinyApp(ui, server)

```

**Comment by JAgOneill** [comment]
hello Yang-Tang ,
here is my actual code where i am working on some RNA
`jqui_resizable(plotOutput("Rna_AtacPlot_single")),`
i apologize for previous mistake .
the reproducible example had a typo! in my actual code i am not using any spaces in between , for a plot id .
i hope you can find solution as the package is very useful for visualization purpose .
thank you

**Comment by Yang-Tang** [comment]
OK, I see. From the reproducible example you provided, I can't find any more problem except the spaces in the id and a missing bracket in the end. I think I may need more details about your code to find out the real problem.

**Comment by Yang-Tang** [comment]
hi @JAgOneill , I think I found a bug that may related to the problem you mentioned. I have pushed an update to the github. Could you have a try and tell me whether it fixed your problem?

**Comment by JAgOneill** [comment]
hello Yang-Tang ,if i remove  jqui_draggable function and shinyjqui package , code works totally fine . but including the function jqui_draggable and shinyjqui package i get the following error (including above update)

 `      

Attaching package: ‘shinyjs’

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show

Loading required package: ggplot2

Attaching package: ‘plotly’

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout

```

Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable

Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
```
```
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox
```
```
Warning: Error in jqui_draggable: could not find function "jqui_draggable"
  77: introBox `
```

**Comment by Yang-Tang** [comment]
I still can't find a clue about this...

**Comment by JAgOneill** [comment]
I used the updated version (github)and it has started working now  . Thank
you for  Github update .
Also I  did some modification in my code
I was using two functions earlier
Jqui_resizable(jqui_draggable(plotOutput))
Instead of that I am using
Jqui_resizable (plotOutput)
It works now but I can use only one function at a time .

**Comment by Yang-Tang** [comment]
Nice to know it works now, then I'll prepare to push the update to CRAN.

`jqui_resizable` and `jqui_draggable` can be used together like this:
```
library(shiny)
library(shinyjqui)
library(ggplot2)

server <- function(input, output) {
  output$foo <- renderPlot({
    ggplot(mtcars, aes(x = cyl, y = mpg)) + geom_point()
  })
}
ui <- fluidPage(
  jqui_resizable(
    jqui_draggable(
      plotOutput('foo', width = '200px', height = '200px')
    )
  )
)

shinyApp(ui, server)
```
