### ISSUE TITLE
Animation effects do not work in my shinyApp

### ISSUE THREAD

**Issue by rgutijim** [Yang-Tang/shinyjqui#26]
Hi, 
I want to add an animation effect but it does not work. I have tried the available example and it does not work either.

I don't know if I am using it the wrong way. 

Thank you for your help!

**Comment by Yang-Tang** [comment]
Could you provide an example code?

**Comment by rgutijim** [comment]
Here is a simple example, very similar to your example code.

ui <- fluidPage(
  plotOutput('plot'),
  actionButton('show', 'Show'),
  actionButton('hide', 'Hide')
)
server <- function(input, output) {
  observeEvent(input$show, {
    jqui_show('#plot', effect = 'blind')
  })
  observeEvent(input$hide, {
    jqui_hide('#plot', effect = bounce)
  })
  output$plot <- renderPlot({
    ggplot(iris, aes(x = iris$Sepal.Length, y = iris$Sepal.Width, 
                     color = iris$Species)) +
      geom_point()
      
  })
}
shinyApp(ui, server)

It doesn't work, when I click on the buttons the graph doesn't react.

**Comment by Yang-Tang** [comment]
Hi @rgutijim , thank you for the bug report. I found it was duo to an internal change from v0.3.0 upgrade. I didn't notice that before. I just pushed an update to github. Could you have a try to see whether it fixed your problem? I'll try to push it to CRAN as soon as possible.

**Comment by rgutijim** [comment]
I have installed the package from github and animation effects work perfectly.

Thank you!

**Comment by Yang-Tang** [comment]
Nice to know that :)
