### ISSUE TITLE
Minify shinyjqui.js?

### ISSUE THREAD

**Issue by doug-friedman** [Yang-Tang/shinyjqui#3]
As a nice to have, it might be worth it to compress/minify the [shinyjqui.js file](https://github.com/Yang-Tang/shinyjqui/blob/master/inst/www/shinyjqui.js)? I ran it through [JSCompress](https://jscompress.com/) and got a 6kb reduction is file size.

**Comment by Yang-Tang** [comment]
Good idea! I'll try to do that. Thanks for the suggestion.

**Comment by doug-friedman** [comment]
Thanks!

**Comment by trafficonese** [comment]
I would like to reopen this as the minified version is commented out in `jquiHead()` and the full version is included again.

Can we make this a parameter somewhere, to ask if minified or full version should be included?

**Comment by Yang-Tang** [comment]
Hi @trafficonese , thanks for the suggestion. I have added a `shinyjqui.debug` option to control which version of `shinyjqui.js` to load.
