### ISSUE TITLE
Multiple shiny apps on the same page - getting rid of the gap

### ISSUE THREAD

**Issue by nickriches** [Yang-Tang/shinyjqui#30]
Hi

I'm planning to use your great package to create some sentence building exercises for linguistics students using R markdown. However, I have run into an issue where, if I have multiple shiny apps on the same page, there is a large gap between them ([shinyjgui_example.zip](https://github.com/Yang-Tang/shinyjqui/files/2269689/shinyjgui_example.zip)). I was wondering if you have any tips / suggestions on how to get rid of this? Many thanks.

**Comment by Yang-Tang** [comment]
I think you can set the `height` option of `shinyApp()`. See example [here](https://bookdown.org/yihui/rmarkdown/shiny-embedded.html#shiny-embed-inline)

**Comment by nickriches** [comment]
Thanks for reply! I've tried that, and it doesn't seem to do it. I don't think it's an issue with the Jqui package, and more of a general Shiny query, so I'll try posting on another forum.
