### ISSUE TITLE
How to load positions from a text file?

### ISSUE THREAD

**Issue by AlexSemenovIRL** [Yang-Tang/shinyjqui#32]
Hi, I'm really enjoying the package, thank you!

I have a small dilemma and not an issue, I would like to save the positions of the elements after drag into a text file which should enable the state save without the bookmarks. How can I achieve that? I don't see it in the code readily available?

- As positions already get pushed in the server side and can be access via `input$foo_position` I was wondering if I can use this info to restore it across sessions
- How can I put the `$top` and `$left` back into the app by load or some other function. Is there an option that I am overlooking

Cheers,

Pork Chop

**Comment by AlexSemenovIRL** [comment]
Can do it via absolutePanel

**Comment by Yang-Tang** [comment]
Hi @AlexSemenovIRL I think you can use the `load` operation in `jqui_draggable` like this:

```
library(shiny)
library(shinyjqui)

ui <- fluidPage(
  jqui_draggable(div(id = "foo", "foo"))
)

server <- function(input, output, session) {
  # you can read foo_position from a text file here
  foo_position <- list(left = 100, top = 100)
  
  # load position by setting state in `options`
  jqui_draggable("#foo", operation = "load", options = list(state = foo_position))
}

shinyApp(ui, server)
```

**Comment by AlexSemenovIRL** [comment]
Ah great, this is so much better, I was using absolute panel with an `id` attached which then was bound to the `jqui_draggable` so I can get the coords, then I was loading it at later stages.

Thank you!
