### ISSUE TITLE
Multiple choice of orderInput items

### ISSUE THREAD

**Issue by akarslan** [Yang-Tang/shinyjqui#35]
Is it possible multiple choice of orderInput items?

**Comment by Yang-Tang** [comment]
Unfortunately, jquery-ui doesn't support multiple sorting naturally. It may introduce bugs if enable this feature package-wise.
If you have knowledge about javascript, I think the most straightforward way is to use custom js code in your shiny app. You can refer to this [link](https://stackoverflow.com/questions/5596748/sort-multiple-items-at-once-with-jquery-ui-sortable).
