### ISSUE TITLE
console.logs in shinyjqui.js

### ISSUE THREAD

**Issue by trafficonese** [Yang-Tang/shinyjqui#39]
This is not a bug, but I am wondering if we could ge rid of the console.logs in shinyjqui.js.

I am refering to the ones in line 105-110:
```
   console.log('===================');
    console.log('ELEMENTS: ');
    console.log($els);
    console.log('MSG: ');
    console.log(msg);
    console.log('===================');
```

**Comment by Yang-Tang** [comment]
Hi @trafficonese , thanks for the suggestion. I have added a `shinyjqui.debug` option to control whether to display these messages.

**Comment by trafficonese** [comment]
Thanks for that quick update. 

Could you maybe show how to include that option in an UI-element (`jqui_resizable` for example).

I tried 
`jqui_resizable(uiOutput("id"), options = list(debug = TRUE))`  and
`jqui_resizable(uiOutput("id"), options = list(shinyjqui.debug = TRUE))`

but that doesn't seem to have an effect, as `msg.debug` will be **undefined** but `msg.options.debug` / `msg.options["shinyjqui.debug"]` would be **true**.

Same goes for the minified version? How do I control that with options?

**Comment by Yang-Tang** [comment]
It's a global option. When `shinyjqui` is loaded, it will add a `shinyjqui.debug = FALSE` to the global option list in current R session. You can just call `options(shinyjqui.debug = TRUE)` to change the behavior.
