### ISSUE TITLE
Non-shiny use cases

### ISSUE THREAD

**Issue by cpsievert** [Yang-Tang/shinyjqui#44]
Great work, this is a really nice package!

I'm curious, have you thought about how `jqui_interaction()` might work on the htmlwidgets and/or htmltools level? It would be nice if this sort of thing "just worked" outside of shiny. In particular, having resizable htmlwidgets would be really nice.

```r
library(shinyjqui)
library(plotly)

qplot(1:10) %>% 
  ggplotly() %>% 
  jqui_resizable()
```

**Comment by Yang-Tang** [comment]
Hi @cpsievert , thank you so much for your suggestion! I finally got time to look into this. The latest github version should now work as the way you mentioned. Could you kindly check if it works in your side?

**Comment by cpsievert** [comment]
Works great (for plotly), thanks!
