### ISSUE TITLE
shinyjqui in mobile devices

### ISSUE THREAD

**Issue by gorantesj** [Yang-Tang/shinyjqui#45]
I'm using shinyjqui for a shinyapp and work fine if I enter from a desktop but if enter from a mobile device either a tablet or a cellphone features like orderInput won't work. Is there any way to use the draggable functionality in mobile device with this package?

**Comment by rquitales** [comment]
Checkout #40 

Uses TouchPunch to enable mobile use.

**Comment by Yang-Tang** [comment]
Hi @rquitales thank you for bringing me the solution! Now this feature has been integrated with this commit 4e9192dbb1d4cb2ef827da14662a0f063d63a8da.
