### ISSUE TITLE
Jquery.flowchart #featurerequest

### ISSUE THREAD

**Issue by carlosantagiustina** [Yang-Tang/shinyjqui#46]
Hi @Yang-Tang ,
congratulations for the very nice package, as a feature request I was wondering if you could integrate jquery.flowchart.js  (https://github.com/sdrdis/jquery.flowchart) functionalities in shinyjqui. I think it would be a very useful improvement for the R community because nothing similar exists at the moment for building personalizable pipelines/processes in Shiny.
Thank you!
best

**Comment by Yang-Tang** [comment]
Hi @carlosantagiustina I'm afraid it would be difficult to integrate jquery.flowchart.js into shinyjqui, because it's a standalone jQuery plugin with very rich functionalities. To create flowchart in R, you may consider the [DiagrammeR package](http://rich-iannone.github.io/DiagrammeR/)
