### ISSUE TITLE
Limit which parts of an object trigger a draggable or sortable event

### ISSUE THREAD

**Issue by madmark81** [Yang-Tang/shinyjqui#47]
Hello Yang-Tang,

first of all, thank you for developing this fascinating package for R. This is more a question than an issue, but it seemed the best way to reach you. I have tried to combine zoomable ggplots with jqui_sortable, and I was wondering it there is a way to make jqui only work when the mouse click is in a part of the div (i.e. the top or edges) and not in other parts (i.e. when the mouse is over the plot that is inside the div, in order to allow both the ggplot 'brush'  to function, as well as the jqui_sortable. 

Sincerely, 

Mark

**Comment by Yang-Tang** [comment]
Hi @madmark81 , it's doable by specifying the `handle` option in `jqui_draggable` and `jqui_sortable`. Please see the following example:

```
library(shiny)
library(shinyjqui)

ui <- fluidPage(
  
  jqui_draggable(
    
    div(
      id = "foo",
      div(id = "drag", "->drag here<-"),
      plotOutput("plot")
    ),
    # Restricts dragging start click to the element with id "drag".
    options = list(handle = "#drag")
    
  )
  
)

server <- function(input, output, session) {
  output$plot <- renderPlot(plot(1:10))
}

shinyApp(ui, server)
```
More details about this option can be found in jquery ui's document page:
https://api.jqueryui.com/draggable/#option-handle
https://api.jqueryui.com/sortable/#option-handle

**Comment by madmark81** [comment]
Great! I'll dive into it later today

Op wo 24 jul. 2019 07:21 schreef Yang Tang <notifications@github.com>:

**Comment by madmark81** [comment]
Can the object to grab also be an actionButton? I tried to use:
just a button, no effect
a button in the div (the div can be grabbed, but not with the mouse on top
of the button
the div as 'label'  of the button, no effect

**Comment by Yang-Tang** [comment]
The `button` and `input` tags are by-default omitted by `draggable` in jquery-ui js library. `shinyjqui` followed this setting. You can change it in the `cancel` option like this: 

```
library(shiny)
library(shinyjqui)

ui <- fluidPage(
  
  jqui_draggable(
    
    div(
      id = "foo",
      actionButton("drag", "->drag here<-"),
      plotOutput("plot")
    ),
    
    # allow anything to be draggable
    options = list(handle = "#drag", cancel = "")
    
  )
  
)

server <- function(input, output, session) {
  output$plot <- renderPlot(plot(1:10))
}

shinyApp(ui, server)
```
More about the `cancell` option can be found here:
https://api.jqueryui.com/draggable/#option-cancel
