### ISSUE TITLE
space between divs changes after sortable

### ISSUE THREAD

**Issue by ghost** [Yang-Tang/shinyjqui#49]
Hi Yang-Tang, 

I managed to make nice use of sortable with the help you provided, but I ran into 1 little issue / buggy behaviour with the app. I wrote a minimalistic example to illustrate it. After sorting the div's in the app below, the space between them changes, causing a distorted outlining of the div's 
I can't figure out what is causing it though and would appreciate it if you can have a look at what causes this. 

`require('shiny')
require('shinyjqui')

ui <- fluidPage(
            div(uiOutput('multiobject'), style = 'width: 1200px')
    )

server <- function(input, output, session) {
  
  output$multiobject <- renderUI({
  plot_output_list <- list();
  
  for(i in 1:8) {
      plot_output_list <- append(plot_output_list,list(
            wellPanel( 
              actionButton('drag', label = icon('hand-point-up'), style = 'float: right; color: #339fff;'),
              style = 'border-color:#339fff; border-width:1px; background-color: #fff;display: inline-block; margin:2px; width:290px; height:250px')
      ))
}
    jqui_sortable(do.call(function(...) div(id="allplots",  ...), plot_output_list), options = list(handle = '#drag', cancel = ""))
    
  })
}
    
shinyApp(ui, server)`

**Comment by madmark81** [comment]
![image](https://user-images.githubusercontent.com/29946999/62157872-6b24d200-b30e-11e9-8178-8e792ba1091e.png)

**Comment by Yang-Tang** [comment]
Hi @madmark81 , this is because an invisible blank space was added between each items when you used the `inline-block` style. See [here](https://css-tricks.com/fighting-the-space-between-inline-block-elements/) for more information. You can set `font-size: 0px` to remove the blank spaces like this:
```
jqui_sortable(do.call(function(...) div(id="allplots", style = "font-size: 0px", ...), plot_output_list), 
                  options = list(handle = '#drag', cancel = ""))
```

**Comment by madmark81** [comment]
Thanks yang. I found out with help on SO yesterday. Works a lot better now

Op do 8 aug. 2019 16:58 schreef Yang Tang <notifications@github.com>:
