### ISSUE TITLE
Feature request: make it work for DT datatable

### ISSUE THREAD

**Issue by hjia222** [Yang-Tang/shinyjqui#52]
This package is very useful, thanks for deveopling this. I wonder if this can work with DT::datatable?
If it's possible to move cells around in datatable that will be very interesting.

**Comment by Yang-Tang** [comment]
Hi @hjia222 , unfortunately, `jquery-ui` library can't support the feature you mentioned very well. What can be done now is to generate sortable rows (like the one showed in the `README.md`) or to make the cells sortable within each row (see the discussion [here](https://stackoverflow.com/questions/32284982/jquery-ui-how-to-define-sortable-td-tags-of-a-table)). If this is what you want, I can try to write some code for `DT::datatable`.

**Comment by hjia222** [comment]
@Yang-Tang Thanks for your quick response!  I would like somthing like a fluid table (or tile if we think a cell in the table is a tile). So you can drag a cell and drop it to another location in the table. Imaging a 96 well plate, which has 12 cols and 8 rows, I want to move well A8 to F12, and all the other wells will adjust their position accordingly.

**Comment by Yang-Tang** [comment]
Is this what you are looking for?

```
library(shiny)
library(shinyjqui)

wells <- lapply(1:96, function(x) {tags$button(x, style = "width:50px", .noWS = "outside")})

ui <- fluidPage(
  jqui_sortable(
    div(id = "plate",
        style = "width:600px",
        wells),
    options = list(cancel = "")
  )
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

**Comment by hjia222** [comment]
Yes, this is very nice, thank you!
