### ISSUE TITLE
Color option ignored for highlight effect

### ISSUE THREAD

**Issue by andrewreece** [Yang-Tang/shinyjqui#56]
Hello, thank you for creating this excellent package.  I've come across an issue that I can't seem to resolve.  For the "highlight" effect, the default highlight color is yellow (specifically `#ffff99`).  This should be adjustable, using the `color` option, but I can't get the highlight color to change from the default.  Any ideas on how to fix this?

Reproducible example:
```library(shiny)
library(shinyjqui)

ui <- fluidPage(
  div(id = "foo", "Hello Shiny", click = "foo_click"),
  
  actionButton("bar", "Click to highlight")
)

server <- function(input, output, session) {
  observeEvent(input$bar, {
    jqui_effect("#foo", effect = "highlight", 
                options = list(color = "green"), # hex codes also don't work
                duration = 1500)
    }
  )
}

shinyApp(ui, server)

**Comment by Yang-Tang** [comment]
Hi @andrewreece , it is a bug. The color should now be adjustable with the last commit b1372f941dea508916a42f24bf9ad2fec8d2706b
