### ISSUE TITLE
updateOrderInput doesn't work if the number of items is less than 2

### ISSUE THREAD

**Issue by dominiqueemmanuel** [Yang-Tang/shinyjqui#57]
Hi,

Thank you for this great package.

I'm trying to use the `updateOrderInput` function.

It works fine if the number of item is greater than or equal to 2.

But when the number of items is equal to 1, it doesn't work.

Here is a reproducible example with two updates, the first one works but the second doesn't work.
```
library(shiny)
library(shinyjqui)

ui <- fluidPage(
  tagList(
    orderInput("A", "A", items = letters[1:5], connect = "B"),
    orderInput("B", "B", items = letters[6:10], connect = "A"),
    br(),
    actionButton("update_ok", "update OK"),
    actionButton("update_ok", "update KO")
  )
)


server <- function(input, output, session) {
  observeEvent(input$update_ok, {
    updateOrderInput(session, "A", items = letters[1:2])
    updateOrderInput(session, "B", items = letters[3:10])
  })
  observeEvent(input$update_ko, {
    updateOrderInput(session, "A", items = letters[1])
    updateOrderInput(session, "B", items = letters[2:10])
  })
}

# Run the application
shinyApp(ui = ui, server = server)
```
Do you have any idea how to solve this?

Best regards,
Dominique

**Comment by Yang-Tang** [comment]
Hi @dominiqueemmanuel thanks for bringing this to me. The bug is now fixed with this commit 4a60968d568aa67c0b2187de56d25690ff77bc0b
