### ISSUE TITLE
Adjustable Splitter 

### ISSUE THREAD

**Issue by tschuler** [Yang-Tang/shinyjqui#60]
Feature or tip request:

I have been looking extensively around the WWW re a way to implement a "splitter" component similar to the following for shiny: https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxsplitter/jquery-splitter-getting-started.htm

Is that something that could be done through shinyjqui or could you point me to any resource how to get started.

Many thanks for this amazing package. Best, Thilo

**Comment by Yang-Tang** [comment]
Hi @tschuler looks like this widget can be achieved through htmlwidgets. Check their [homepage](https://www.htmlwidgets.org/) for more details.
