### ISSUE TITLE
How to add only vertically draggable in Jqui

### ISSUE THREAD

**Issue by SubhadipDatta** [Yang-Tang/shinyjqui#61]
I am using this to options but not working. Please help me. How to use this in shiny app R
?

`jqui_draggable(ui,options="axis:'y'")`

https://api.jqueryui.com/draggable/#option-axis

**Comment by trafficonese** [comment]
You have to wrap the options in a named list:
`jqui_draggable(ui, options = list(axis = 'y'))`

**Comment by DJSUBHAOO7** [comment]
> You have to wrap the options in a named list:
> `jqui_draggable(ui, options = list(axis = 'y'))`

Thank you, this is working now but not working in mobile devices. I heard about touch punch, can you help me how to use it in shiny app. Actually I am confused with it.
