### ISSUE TITLE
Enable `NULL` label in `orderInput()`

### ISSUE THREAD

**Issue by tomicapretto** [Yang-Tang/shinyjqui#63]
When you specify a `NULL` label in, for example, `selectInput()`, the result is an input object without header. 
The current implementation of `orderInput()` lets the user to specify a `NULL` label but it does not result in the label being removed and consequently you get a blank space in the UI.

Currently, `orderInput()` handles the `label` argument as follows:

```
...
  label <- shiny::tags$label(label, `for` = inputId)
...
```

I think that you can switch it to 

```
...
  if (!is.null(label)) label <- shiny::tags$label(label, `for` = inputId)
...
```
In order to behave similarly to other input functions in `shiny`.

**Comment by Yang-Tang** [comment]
Thanks for the good suggestion! I have included this feature in the next release of the package.
