### ISSUE TITLE
orderInput not taking _order information?

### ISSUE THREAD

**Issue by hlliu6** [Yang-Tang/shinyjqui#64]
Hello,

I just updated my R (3.6.3) and all packages, and notice orderInput is not returning  _order information. Any idea?
It was working under older R....
Thanks,
Lu

**Comment by hlliu6** [comment]
Got NULL running the example code:
![image](https://user-images.githubusercontent.com/63250254/78583024-d870f700-77fb-11ea-96de-35394c17670e.png)

![image](https://user-images.githubusercontent.com/63250254/78583084-f179a800-77fb-11ea-98ea-ebbbc2022c34.png)

**Comment by Yang-Tang** [comment]
Sorry, I can't help without an example code
