### ISSUE TITLE
Use orderInput in Table & module

### ISSUE THREAD

**Issue by emantzo** [Yang-Tang/shinyjqui#70]
I am having some difficulties in using orderInput to define formulas in aTable.
Would you please check my [SO question](https://stackoverflow.com/questions/63496291/r-shiny-use-orderinput-in-table-module)?

Many thanks!!

**Comment by emantzo** [comment]
Thanks a lot for the reply!
I tried it and I noticed that when I use the Reset button the "operators" are not removed  from the formula.
Also, is there any option to select and remove only certain items from the formula?


________________________________

**Comment by Yang-Tang** [comment]
You need to install the newest github version of shinyjqui in which I fixed the bug. To remove certain items, you may try the `updateOrderInput` function.

**Comment by emantzo** [comment]
Thank you for your reply.
Regarding removing items from the formula, I would like to ask if this is possible to do by dragging them  out of the formula.

________________________________
