### ISSUE TITLE
bootstrap() and jqui_interaction mess with the tooltips

### ISSUE THREAD

**Issue by trafficonese** [Yang-Tang/shinyjqui#73]
I am not sure if this is caused by `bslib` (former `bootstraplib`) or `shinyjqui`, but the tooltips won't render correctly when both are used together.

In the following sample app, `jqui_resizable()` is removed / commented out, the tooltips are displayed correctly.

```
library(shiny)
library(bslib)
library(shinyjqui)
bs_global_theme(version = "4", bootswatch = NULL)

ui <- fluidPage(
  tags$head(
    bs_theme_dependencies(bs_theme()),
    tags$script('$(function() {
                    $("[data-toggle=\'tooltip\']").tooltip();
                 });')
  ),
  br(),br(),
  jqui_resizable(
    div(style="border:1px solid black",
        "With bootstrap and a shinyjqui interaction, the tooltips dont appear correctly")
  )
  ,br(),
  HTML('
    <div style="height: 40px; width:100%; background-color:#acacac" data-toggle="tooltip" data-html="true"
      data-placement="bottom" title="This is a <b>ToolTip</b><ul><li>List</li></ul>">
      A tooltip will appear below on Hover.
    </div>
  ')
)

server <- function(input, output, session) {}
shinyApp(ui, server)
```

Any help is greatly appreciated!

**Comment by Yang-Tang** [comment]
Hi @trafficonese this is an old bug between bootstrap and jquery ui. See posts here:
https://github.com/twbs/bootstrap/issues/6303
https://stackoverflow.com/questions/13731400/jqueryui-tooltips-are-competing-with-twitter-bootstrap
Looks like the solution is to use the `noConflict` option on the Bootstrap widget
