### ISSUE TITLE
How to keep background elements available when a popup window is open

### ISSUE THREAD

**Issue by heeringa0** [Yang-Tang/shinyjqui#75]
I am using a modal in a Shiny script using the function draggableModalDialog from the shinyjqui.

This works fine, but the background (i.e. parent window) get grayed out, the inputs in the parent window cannot be used as long as the popup window is open.

I think in most cases this is the desired/expected behavior, but in my case the parent window should not be grayed out. I struggled to solve this, but did not succeed.

Is there a solution for it? What would you recommend?

Attached you find the script.
[test.txt](https://github.com/Yang-Tang/shinyjqui/files/5971100/test.txt)

**Comment by Yang-Tang** [comment]
Hi @heeringa0 , I guess it needs some settings in CSS, but I'm not very familiar to this. After a quick search, I found these posts may help:
https://stackoverflow.com/questions/32459337/how-to-remove-bootstrap-modal-overlay
https://stackoverflow.com/questions/47996609/how-to-remove-backdrop-only-from-modal/47997221
https://weblog.west-wind.com/posts/2016/sep/14/bootstrap-modal-dialog-showing-under-modal-background
Good luck!

**Comment by heeringa0** [comment]
Hi Yang Tang,

Thanks for your response and the useful suggestions.

Best regards,
Wilbert


Op zo 14 feb. 2021 om 14:19 schreef Yang Tang <notifications@github.com>:
