### ISSUE TITLE
can't move an element into a blank `orderInput`

### ISSUE THREAD

**Issue by hbaniecki** [Yang-Tang/shinyjqui#78]
Hi, great package!

Either I did something wrong or you can't add a category to a blank `orderInput` (without any labels), e.g. move "alpha" back to the 1st group in the image below. Any ideas on how to fix this?

**Edit.** I have just found the [`placeholder` ](https://yang-tang.github.io/shinyjqui/reference/orderInput.html) parameter and it works in this case. Maybe this should be the default behaviour.

![orderinput](https://user-images.githubusercontent.com/32574004/131090463-7b86f896-d69e-474f-8e05-3607a2e88492.gif)

**Comment by Yang-Tang** [comment]
Hi @hbaniecki `orderInput` has a default `min-height: 25px` style setting. It should not have such "move-back" problem. Maybe you have overwritten the default style settings in your case? If so, you would need the placeholder.
