### ISSUE TITLE
orderInput and renderUI

### ISSUE THREAD

**Issue by peeyooshc** [Yang-Tang/shinyjqui#8]
HI there,
 Really impressed with the functionality in your package, and how easy it makes it to add draggable and sortable functionality.

 I am trying to use orderInput which is rendered using a renderUI call, with items being populated by an eventReactive function.

 When I re-render the object (after eventReactive) updates, none of the rendered items are draggable or sortable.

 Is there a specific way to execute this or is it something that is not possible?

 Thanks in advance.

**Comment by Yang-Tang** [comment]
Hi @peeyooshc , thank you for opening the issue. I think it is a bug of the current shinyjqui v0.2.0 on CRAN. The development version on the Github already fixed it. I'm planing to submit a new version to CRAN recently. Would you mind to test whether the Github version has solved you problem?

**Comment by peeyooshc** [comment]
Thanks for the quick answer, and Github version is working correctly. Will keep plugging on :)

**Comment by Yang-Tang** [comment]
That's great! Thanks for the feedback!
