### ISSUE TITLE
shinycssloaders compatibility

### ISSUE THREAD

**Issue by m-swirski** [Yang-Tang/shinyjqui#88]
Hi, I noticed strange behavior when combining shinyjqui in combination with shiny css_loaders.
Specifically, I use withSpinner function to display animation during wait.
Consider code snippets below:
```
library(shiny)
library(shinyjqui)
library(ggplot2)
library(shinycssloaders)

ui <- fluidPage(
  actionButton("go", "Go"),
  jqui_resizable(plotOutput('gg')) %>% shinycssloaders::withSpinner(color="#0dc5c1")
)

server <- function(input, output) {
  
  val <- eventReactive(input$go, mtcars)
  output$gg <- renderPlot({
    Sys.sleep(1.5)
    ggplot(val(), aes(x = cyl, y = mpg)) + geom_point()
  }
  )
}


shinyApp(ui, server)



ui <- fluidPage(
  actionButton("go", "Go"),
  jqui_resizable(plotOutput('gg') %>% shinycssloaders::withSpinner(color="#0dc5c1"))
)

server <- function(input, output) {
  
  val <- eventReactive(input$go, mtcars)
  output$gg <- renderPlot({
    Sys.sleep(1.5)
    ggplot(val(), aes(x = cyl, y = mpg)) + geom_point()
  }
  )
}

shinyApp(ui, server)
```

In the first example animation appears before the first go putton push, and then the plot just goes gray, with the resizing working, while in the second example spinner works just fine, while resizing stops working. The only difference is whether jqui_resizable encapsulates withSpinner function or not. 

Any ideas if it's possible to fix that problem?

Thanks,
Michał

**Comment by Yang-Tang** [comment]
Hi @m-swirski with 2fdcabf80f2f09b5cbf4de3ce4dfc94ed5cad69d, both of the two ways you showed should work now. Let me know if it isn't what you expected

**Comment by m-swirski** [comment]
Hi,
Thanks for attending to this issue!
I pulled the new version and tested - the first way doesn't work different (greying and no css spinner), while the second does work, but resizing is active only on horizontally, i.e. on x axis (it shrinks and expands as if options = list(handles = "e"))
Does it work the same on your end, or am I perhaps missing something?

PS.
On related note - these options = list(handles...) doesn't work as expected, so far I only managed to make it work with "e" and "n" parameters, in both cases the resizing handle disappears and one has to grab border of the resizable element. 

Best,
Michal

**Comment by Yang-Tang** [comment]
Sorry, I forgot to update the js file. Now it should works. For the handle options, I guess it is the default behavior of jQuery UI. According to their document, you can generate your own handle with `ui-resizable-handle` class.

**Comment by m-swirski** [comment]
Okay, now it worked like a charm, thanks a million for helping with this!

Thanks for a tip on creating a handle, I'll experiment with this.

Best, 
Michał

**Comment by CroixJeremy2** [comment]
Hello,
Just one small comment for future readers. I had the same problem in late 2024 (with latest versions of all involved packages), and all those tests bellow did not work somehow:
-  `jqui_resizable(withSpinner(plotOutput(outputId = "my_graph")))`
-  `withSpinner(jqui_resizable(plotOutput(outputId = "my_graph")))`
- `jqui_resizable(plotOutput(outputId = "my_graph") %>% withSpinner())`
- `withSpinner(plotOutput(outputId = "my_graph") %>% jqui_resizable())`

And even after having loaded some other packages that have the `%>%` operator like tidyverse for example. I dug into some forums (like this [one](https://stackoverflow.com/questions/27125672/what-does-function-mean-in-r) that summarises many things, and apparently now (after R 4.1.0) the `|>` operator is recommended. I tried, and it worked like a charm!

So I use now this syntax:
- `jqui_resizable(plotOutput(outputId = "my_graph") |> withSpinner())`

Elegant, I like it, and it work. I hope that it will help others struggling with that small issue.
Best regards,
