### ISSUE TITLE
Unable to pass vector onto `connect` parameter in `updateOrderInput` function

### ISSUE THREAD

**Issue by SanjayShetty01** [Yang-Tang/shinyjqui#89]
The shinyjqui in R >4.2 throws an error whenever we pass a vector onto connect parameter. 

``` r
library(shinyjqui)

str_cols = c('a', 'b')

shinyjqui::updateOrderInput(session,"categorical_columns",label = "Categorical columns",
      connect = c("numeric_columns","exclude_columns","date_columns"),items = str_cols,item_class = c("default"))

```
```
> Error in if (connect == FALSE) { : the condition has length > 1
```

The same code chunk in R <4.2 throws a warning instead of an error. 

The error could be due to the following code chuck in the `updateOrderInput` function

``` r 
    if(connect == FALSE) {
      connect <- "false"
```
 Since connect has multiple values the condition length would be greater than 1. which in R > 4.2 would throw an error instead of a warning.

Warning in R < 4.1

``` r
Warning in if (connect == FALSE) { :
  the condition has length > 1 and only the first element will be used
```

If the code's purpose was to find if the vector contains any `false` value, then we could replace `==` with `%in%`.

**Comment by Yang-Tang** [comment]
Thank you for bringing this issue to my attention and for providing such a comprehensive analysis. The bug has been fixed now.
