### ISSUE TITLE
Hoping for some help

### ISSUE THREAD

**Issue by peeyooshc** [Yang-Tang/shinyjqui#9]
Hi There,
 I've been trying to get a version of your orderInput function going, where you can select multiple items and drag them to a specific div. The sort order is not important.

 I'm failing somewhat as I don't understand how selectable and draggable are meant to work together. Would you happen to have an example of how to get selectable, draggable and droppable work together. 

 The client side javascript is mostly what is catching me out.

 Thanks in advance and hoping you can.

 _ PC

**Comment by Yang-Tang** [comment]
Hi @peeyooshc , it looks doable but not very straight forward. I'll figure out a solution and send it to you later.

**Comment by peeyooshc** [comment]
Thanks for trying Yang, glad to see I'm not the only one who struggled.

I'll share where I got to over the weekend in case that helps.
