### ISSUE TITLE
cannot updateOrderInput with connect argument

### ISSUE THREAD

**Issue by degi** [Yang-Tang/shinyjqui#93]
I've got:
Warning: Error in if: the condition has length > 1
is it a bug?

**Comment by SanjayShetty01** [comment]
Hey try downgrading R to < 4.2.

this issue looks similar to #89

**Comment by Yang-Tang** [comment]
Yes, it's same issue as #89 . Now it has been fixed.

**Comment by degi** [comment]
Great! Tx!
