### ISSUE TITLE
Possible caching issue affecting drag-and-drop functionality in Shiny app

### ISSUE THREAD

**Issue by TarJae** [Yang-Tang/shinyjqui#94]
I've posted a question on [StackOverflow](https://stackoverflow.com/questions/76893221/shiny-app-how-to-control-drag-and-drop-with-shinyjgui). In summary, my Shiny app's drag-and-drop functionality (using shinyjqui) only works reliably after restarting R in RStudio and clearing previous browser sessions. Notably, it works consistently when I launch a new anonymous browser session. This leads me to believe there might be a caching issue.

**Comment by TarJae** [comment]
It is an issue with firefox. Using edge browser. The issue did not occur!

**Comment by TarJae** [comment]
I will now close both the issue here and the question on stackoverflow.

**Comment by choiceMaster-ai** [comment]
I am obtaining the error:  Error in discrete_range: could not find function "discrete_range" when executing the code: jqui_draggable(ui = '.modal-content')
It used to work. Thank you.
